version: '3'
services:
  api:
    image: n0stack/n0stack
    command:
      - /usr/local/bin/n0core
      - serve
      - api
    ports:
      - "8080:8080"
      - "20180:20180"
    volumes:
      - /var/lib/n0core/api:/var/lib/n0core
